# Generated by Django 3.2.16 on 2023-06-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230531_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
